name: Fetch Data
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync-patrons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch and Update
        run: |
          curl -s "https://cdn.fallensworkshop.com/872557386244698162/patrons" -o incoming.json
          
          if [ -f PatreonData.json ]; then
            jq 'del(.LastUpdated)' PatreonData.json > current_no_time.json
            jq 'del(.LastUpdated)' incoming.json > incoming_no_time.json
            
            if cmp -s current_no_time.json incoming_no_time.json; then
              echo "No actual data changes detected. Skipping commit."
              exit 0
            fi
          fi
          
          mv incoming.json PatreonData.json

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "GitHubAction@fallensworkshop.com"
          git add PatreonData.json
          git commit -m "Automated update: PatreonData.json" || exit 0
          git push
